//Detect Browser
var isOpera = !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0;
    // Opera 8.0+ (UA detection to detect Blink/v8-powered Opera)
var isFirefox = typeof InstallTrigger !== 'undefined';   // Firefox 1.0+
var isSafari = Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0;
    // At least Safari 3+: "[object HTMLElementConstructor]"
var isChrome = !!window.chrome && !isOpera;              // Chrome 1+
var isIE = /*@cc_on!@*/false || !!document.documentMode;   // At least IE6

if (isFirefox){
  window.alert('Apologies, we have been having issues with Firefox and this Script.\nPlease use IE or Chrome for the time being.')  
};



//Charts not working to removing below temporarily
//google.load('visualization', '1', {packages: ['corechart', 'bar']});
//google.setOnLoadCallback(calc);//changed to "calc" from "drawBasic"




//Original DH Function

function calc(){
    var textType = Node.textContent ? 'textContent' : 'innerText';
    var ebitda = parseFloat(document.getElementById('ebitda').value) || 0;
    var mult = parseFloat(document.getElementById('mult').value) || 0;
    var leh = [0.05, 0.04, 0.03, 0.02, 0.01];
    var fee = document.getElementById("fee");
    var totalEnt = document.getElementById("tev");
    var TEV = ebitda * mult;

    
    //Display TEV
    totalEnt[textType] = Math.round(TEV*1000)/1000;//this x100/divid by 100 is to round it to 3 decimals
    
  
    // 3rd Iteration - New loop calculator. Should increment by one through the 1-5 steps
    //looper not working
    
    var makeFee = 0; //sum of fees
    var feeMaker = [0,0,0,0,0]; //Array of all fees by step
    for (i=0, j=0; i < TEV+1; i++){
        if (i>=4){
            j=4; //"j" ends up being the selector for the Lehman Fee step (i.e. 0 give us 5%)
            } else {j=i;};
        if (TEV-i>=1){
            makeFee += Math.max(leh[j]*1,0);
            feeMaker[j] += Math.max(leh[j]*1,0)*1000000; //these don't go through the numberWithCommas expander, so they need a multiplier of 1 million
        } else {
            makeFee += Math.max(leh[j]*(TEV-i),0);
            feeMaker[j] += Math.max(leh[j]*(TEV-i),0)*1000000;
        };
    
    }
    fee[textType] = numberWithCommas(Math.max(makeFee,0));

    
    
    
    //2nd Interation - each calc'd with if statement then added together
    /*
    var feeMaker = [0,0,0,0,0];
    if(TEV>=1){
            feeMaker[0] = 1 * leh[0];
        }else{
            feeMaker[0] = Math.max(TEV,0)*leh[0];
        };
        //need to finish off if statements
    
   var makeFee = feeMaker[0] + feeMaker[1] + feeMaker[2] + feeMaker[3] + feeMaker[4];
    fee[textType] = numberWithCommas(Math.max(makeFee,0));
    */

    
    
    //1st Interation
    /*
    if(TEV<1){fee[textType] = numberWithCommas(Math.max(leh[0]*TEV,0))} else
    if(TEV>=1 && TEV<2){fee[textType] = numberWithCommas(leh[1]*(TEV-1) + 0.05)} else
    if(TEV>=2 && TEV<3){fee[textType] = numberWithCommas(leh[2]*(TEV-2) + 0.09)} else
    if(TEV>=3 && TEV<4){fee[textType] = numberWithCommas(leh[3]*(TEV-3) + 0.12)} else
    if(TEV>=4){fee[textType] = numberWithCommas(leh[4]*(TEV-4) + 0.14)};
    */



    
    /* This works with other HTML
    var totalEnt = parseFloat(document.getElementById("tev").value);
    var fee = 0;

    fee = totalEnt * 5;
    
    result = document.getElementById("result");
    result.innerHTML = fee;
    */



//This is all the revised Google Charting code:
//Charts not working so removing this temporarily
/*
      var data = google.visualization.arrayToDataTable([
        ['Fee Step', 'Fee Generated by Step',],
        ['5%', feeMaker[0]],
        ['4%', feeMaker[1]],
        ['3%', feeMaker[2]],
        ['2%', feeMaker[3]],
        ['1%', feeMaker[4]]
      ]);

      var options = {
        title: 'Lehman Fee by Percentage Step',
        chartArea: {width: '50%'},
        hAxis: {
          title: 'Fee',
          minValue: 0,
          format: '$#,###'//'currency' is another way, but that makes it have decimals
        },
        vAxis: {
          title: 'Fee Step'
        }
      };

      var chart = new google.visualization.BarChart(document.getElementById('chart_div'));

      chart.draw(data, options);
*/

}
calc();

function numberWithCommas(x) {
    var lehOpt = document.getElementById("lehman");
    var sD = parseFloat(lehOpt.selectedIndex)+1;

    var y = Math.round(x * 1000000 * sD *100)/100; //the x100/round/div by 100 is to limit to two decimal places
    var parts = y.toString().split(".");
    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    return parts.join(".");
}
